server:
  port: ${SERVICE_PORT:8080}
spring:
  profiles:
    include:
      - commons
      - database
  application:
    name: rest-client-example
datasources:
  rest:
    webServices:
      weather:
        base-url: http://localhost:1080
        api-key: fakeapikey
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

